`define H_W								   	 416 
`define WIDTH_DATA                           8
`define WIDTH_DATA_OUT                      10
`define AXI_WIDTH_ADDR                      64
`define IMAGE_WIDTH_DATA                    8   
`define AXI_WIDTH_DATA                      128
`define AXI_WIDTH_DATA_IN                   256
`define IMAGE_BIAS_WIDTH_DATA               256
`define WIDTH_REG_SIZE                      256
`define WIDTH_IMAGE_DMA_READ                256
`define WIDTH_DMA                           256
`define PICTURE_NUM                         2
`define CONV_3_3                            9
`define CONV_1_1                            1
`define WIDTH_DMA_INSTR                     64
`define Weight_Row_Num						 600  
`define	 En_Stride_REG                       1
`define Channel_Out_Num                     8
